service:
  name: canary

custom:
  app_acronym: canary
  default_stage: qa
  stage: ${opt:stage, self:custom.default_stage}
  stack_name: ${self:custom.app_acronym}-${self:custom.stage}

  default_region: us-east-1
  region: ${opt:region, self:custom.default_region}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage} # Set the default stage used. Default is dev
  region: ${self:custom.region} # Overwrite the default region used. Default is us-east-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 30
  deploymentBucket:
    name: serverless-sr-deploys-personal # Overwrite the default deployment bucket
  versionFunctions: false # Optional function versioning

  stackTags:
    Name: Redirect to canary ALB

  # you can define service wide environment variables here
  environment:
    stage: ${self:custom.stage}
    region: ${self:custom.region}
    alb_dns_name: canary-alb-1183014609.us-east-1.elb.amazonaws.com

# you can add packaging information here
package:
  exclude:
    - .idea/**
    - .git/**
    - .serverless/**
    - tests/**
    - node_modules/**

functions:
  redirect:
    handler: func.handler
    events:
      - http:
          path: /canary
          method: get
